version: "3.7"


services:

  traefik:
    image: traefik:1.7.8-alpine # The official Traefik docker image
    ports:
      - 80:80     # The HTTP port
      - 8080:8080 # The Web UI (enabled by --api)
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    command: --api --docker --logLevel=DEBUG
    networks:
      - proxy
    
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    # Note that a separate image exists for DSpace 4x
    # image: dspace/dspace-postgres-4x
    container_name: dspacedb6
    environment:
      - PGDATA=/pgdata
    volumes:
      - ./pgdata:/pgdata
      - "./dspace/init-scripts:/dspace-docker-tools"
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace6:
    build: "./dspace/"
    container_name: dspace6
    environment:
      # Env vars with double underbars in names will be replaced with periods and written to local.cfg
      # The defaul values for local.cfg will be provided here
      # __D__ -> - (dash)
      # __P__ -> . (point)
      - dspace__P__dir=/dspace
      - db__P__url=jdbc:postgresql://dspacedb:5432/dspace
      - dspace__P__hostname=${HOSTNAME:-localhost}
      - dspace__P__baseUrl=http://${HOSTNAME:-localhost}
      - dspace__P__name=DSpace Started with Docker Compose
    labels:
      - traefik.backend=dspace
      - "traefik.frontend.rule=Host:www.${HOSTNAME:-localhost},${HOSTNAME:-localhost}"
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=8080

    volumes:
      - assetstore:/dspace/assetstore
      - ./dspace/init-scripts:/dspace-docker-tools
      - ./dspace/webapps/rest/WEB-INF/web.xml:/usr/local/tomcat/webapps/rest/WEB-INF/web.xml
      - ./dspace/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml

      - ./backups:/backups
      - solr_authority:/dspace/solr/authority/data
      - solr_oai:/dspace/solr/oai/data
      - solr_search:/dspace/solr/search/data
      - solr_statistics:/dspace/solr/statistics/data
    entrypoint: /dspace-docker-tools/init.sh
    networks:
      - dspacenet
      - proxy
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true


volumes:
  pgdata:
  assetstore:
  # The Solr volumes will be defined in one of the dX.override.yml files
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics:

networks:
  dspacenet:
    external: false
  proxy:
    external: true